Set CMAKE_MODULE_PATH appropriately to always use preferred linalg-modules
wavefunction91/GauXC pull request #38
Opened 2021-02-09 23:48 UTC by ajaypanyala

2021-02-10 18:39 UTC, wavefunction91 requested changes

2021-02-10 18:39 UTC, wavefunction91 commented on CMakeLists.txt
> +list(INSERT CMAKE_MODULE_PATH 0 ${PROJECT_SOURCE_DIR}/cmake )
Isn't this equivalent to `list( PREPEND`?

2021-02-10 18:39 UTC, wavefunction91 commented on src/CMakeLists.txt
>  )
I would change this to
```
if( GAUXC_ENABLE_OPENMP )
  target_link_libraries( gauxc PUBLIC OpenMP::OpenMP_CXX )
endif()
```

2021-02-11 22:38 UTC, wavefunction91 commented
@ajaypanyala Is there anything else you want to add to this? I'm going to hold off on merging until https://github.com/wavefunction91/linalg-cmake-modules/pull/1 is merged

2021-02-11 22:52 UTC, ajaypanyala commented
I am done with my edits. Thanks!

2021-02-12 03:17 UTC, ajaypanyala commented on cmake/gauxc-dep-versions.cmake
> +set( GAUXC_LINALG_MODULES_REPOSITORY https://github.com/ajaypanyala/linalg-cmake-modules )
Note before merging: This needs to change once [wavefunction91/linalg-cmake-modules#1](https://github.com/wavefunction91/linalg-cmake-modules/pull/1) is merged

2021-02-12 03:18 UTC, ajaypanyala commented on cmake/gauxc-dep-versions.cmake
> +set( GAUXC_LINALG_MODULES_REVISION  main )
TODO: Pin commit before merging.

2023-04-28 17:20 UTC, closed without merging