Libxc should be cited alongside GauXC
wavefunction91/GauXC pull request #72
Opened 2023-08-22 15:29 UTC by susilehtola

The GauXC citations don't include Libxc at the moment. Libxc should be included in the list of citations to make sure people don't cite just GauXC...

2023-08-22 15:40 UTC, wavefunction91 requested changes
I'm generally supportive of this, but I would put this as a separate block below the GauXC citations. While Libxc provides an important functionality for a subset of GauXC, indicating that it should be cited for *any* GauXC usage (e.g. even for sn-K) does not seem appropriate.

Something to the effect of 
"If GauXC was used for the evaluation of exchange-correlation related quantities in your publication or software, we request that you additionally cite Libxc (link to Gitlab) which provides the underlying implementation of the exchange-correlation functionals used in GauXC via ExchCXX:"
<Insert your BibTeX here>

In addition, we should clarify some of this in ExchCXX as well, please open an *Issue* in ExchCXX to track, I will work on verbiage and ping you for review.

2023-09-20 16:10 UTC, wavefunction91 requested changes
Other than that, g2g. Thanks for the changes

2023-09-20 17:02 UTC, susilehtola commented
Go ahead and merge

2023-09-20 17:37 UTC, wavefunction91 approved these changes

2023-09-20 17:58 UTC, merged